version: 2.1
orbs:
  architect: giantswarm/architect@4.9.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-control-plane-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "prometheus-operator-crd"
          filters:
            tags:
              only: /^v.*/
