version: 2.1
orbs:
  architect: giantswarm/architect@4.14.3

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: default-catalog
          context: architect
          executor: app-build-suite
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          chart: prometheus-operator-crd
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: giantswarm-catalog
          context: architect
          executor: app-build-suite
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          chart: prometheus-operator-crd
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: control-plane-catalog
          context: architect
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: prometheus-operator-crd
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: shared-collection
          context: architect
          app_name: prometheus-operator-crd
          app_namespace: monitoring
          app_collection_repo: shared-app-collection
          disable_force_upgrade: true
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-collection
          context: architect
          app_name: prometheus-operator-crd
          app_namespace: monitoring
          app_collection_repo: aws-app-collection
          disable_force_upgrade: true
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-collection
          context: architect
          app_name: prometheus-operator-crd
          app_namespace: monitoring
          app_collection_repo: azure-app-collection
          disable_force_upgrade: true
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: kvm-collection
          context: architect
          app_name: prometheus-operator-crd
          app_namespace: monitoring
          app_collection_repo: kvm-app-collection
          disable_force_upgrade: true
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: vsphere-collection
          context: architect
          app_name: prometheus-operator-crd
          app_namespace: monitoring
          app_collection_repo: vsphere-app-collection
          disable_force_upgrade: true
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: openstack-collection
          context: architect
          app_name: prometheus-operator-crd
          app_namespace: monitoring
          app_collection_repo: openstack-app-collection
          disable_force_upgrade: true
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
