# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: prometheus-operator-crd
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/prometheus-operator-crd
  tag: v0.0.1
  pullPolicy: IfNotPresent
